server:
  port: 8081

spring:
  datasource:
        url: jdbc:postgresql://ec2-3-211-221-185.compute-1.amazonaws.com:5432/ec2-3-211-221-185.compute-1.amazonaws.com
        username: tvhehdotmodqmb
        password: 01a89603b1fa319b24b1b79905cad82cd68f0c20697cffe6ce4e1272b51845cc
#    url: jdbc:postgresql://localhost:5432/emedDb
#    username: postgres
#    password: 123

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL92Dialect
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: never

  springdoc:
    version: '@springdoc.version@'
    swagger-ui:
      use-root-path: true

